### PR TITLE
Add header.html, navbar.html and card.html

### PR DESCRIPTION
**Pull request by AlexF090**
add header.html and navbar.html with placeholder.
Renamed header.html to card.html and add header.html  with placeholder.

### CODE REVIEW

**Review by ThomasF85 — CHANGES_REQUESTED** [review]
You have to create html markup in Form of jsx. You need components (which contain your html markup in form of jsx) that you import and use in your App.js.

**Review by ThomasF85 — CHANGES_REQUESTED** [review]
Good Job. Just delete your unnecessary html files and import and use your components in the App.js and you are done.

**Review by ThomasF85 — APPROVED** [review]
Your App.js is fine for now. But you have to delete the markup in this file for future tasks and directly import your Header, NavBar and Card components instead. You kind of have all your markup twice now, once in the App.js and once in every component.

**Comment by AlexF090** [comment]
> 

Thank you very much :D

**Pull request merged**
